url: https://mriscm.github.io
baseurl: /home/

# Site settings
title: Sharp Analytics
email: Sharp1Analytics@gmail.com
description: "MrIsCM's website: Blog, porfolio and contact. Machine Learning, Data Science, Python, Physics, Maths, Stats and much more."


# Team names, titles and social links
people:
- name: Ismael Charpentier
  pic: 1
  position: Data Scientis / Python Programmer
  social:
    - title: twitter
      url: https://x.com/SharpAnalytic
    - title: github
      url: https://github.com/MrIsCM
    - title: linkedin
      url: https://www.linkedin.com/in/ismaelcharpentier/

# # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Andalucia, Spain

# Build settings
markdown: kramdown
permalink: pretty