# url: https://mriscm.github.io
# baseurl: 

# Site settings
title: Sharp Analytics
email: Sharp1Analytics@gmail.com
description: "MrIsCM's website: Blog, porfolio and contact. Machine Learning, Data Science, Python, Physics, Maths, Stats and much more."


# Team names, titles and social links
people:
- name: MrIsCM
  pic: 1
  position: Data Scientis / Python Programmer
  social:
    - title: twitter
      url: https://x.com/SharpAnalytic
    - title: github
      url: https://github.com/MrIsCM
    - title: linkedin
      url: https://www.linkedin.com/in/ismaelcharpentier/
    - title: kaggle
      url: https://www.kaggle.com/MrIsCm

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/SharpAnalytic
  - title: github
    url: https://github.com/MrIsCM
  - title: linkedin
    url: https://www.linkedin.com/in/ismaelcharpentier/
  - title: kaggle
    url: https://www.kaggle.com/MrIsCm
  - title: envelope
    url: mailto:Sharp1Analytics@gmail.com


# Postal address (add as many lines as necessary)
address:
  - line: Granada
  - line: Spain

# Build settings
markdown: kramdown
permalink: pretty